apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: ${PORT}
  type: ${SERVICE_TYPE}
