apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 1  # Dev mode: single instance
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels: 
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          env:
            - name: DEBUG
              value: "true"
          resources: 
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"