services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/app
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
