pipeline {
    agent any
    
    environment {
        DOCKERHUB_USERNAME = 'idanpersi'
        BACKEND_REPO = 'gitops_backend'
        FRONTEND_REPO = 'gitops_frontend'
        DOCKER_TOOL = 'docker-latest'
        TAG = "${BUILD_NUMBER}"
    }
    
       tools {
        dockerTool DOCKER_TOOL
    }
    stages {
        stage('Run Tests') {
            parallel {
                stage('Backend Tests') {
                    steps {
                        dir('backend') {
                            script {
                                def testImage = docker.build("backend-test:${BUILD_NUMBER}")
                                testImage.inside {
                                }
                            }
                        }
                    }
                }
                
                stage('Frontend Tests') {
                    steps {
                        dir('frontend') {
                            script {
                                def testImage = docker.build("frontend-test:${BUILD_NUMBER}")
                                testImage.inside {
                                }
                            }
                        }
                    }
                }
            }
        }

        stage('Build and Push Images') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'DockerHub_creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh 'echo $PASS | docker login -u $USER --password-stdin'

                        dir('backend') {
                            def backendImage = docker.build("${DOCKERHUB_USERNAME}/${BACKEND_REPO}:${TAG}")
                            backendImage.push()
                            backendImage.push('latest')
                        }
                        
                        dir('frontend') {
                            def frontendImage = docker.build("${DOCKERHUB_USERNAME}/${FRONTEND_REPO}:${TAG}")
                            frontendImage.push()
                            frontendImage.push('latest')
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                sh """
                    docker rmi backend-test:${BUILD_NUMBER} || true
                    docker rmi frontend-test:${BUILD_NUMBER} || true
                    docker rmi ${DOCKERHUB_USERNAME}/${BACKEND_REPO}:${TAG} || true
                    docker rmi ${DOCKERHUB_USERNAME}/${BACKEND_REPO}:latest || true
                    docker rmi ${DOCKERHUB_USERNAME}/${FRONTEND_REPO}:${TAG} || true
                    docker rmi ${DOCKERHUB_USERNAME}/${FRONTEND_REPO}:latest || true
                """
            }
        }
    }
}
